"""
Revenue-First Content OS — Lane 4 Programmatic Data Card Renderer
Renders high-contrast 9:16 vertical data cards (1080x1920) using pure Python Pillow.
Zero GPU compute, zero Godot, zero external API costs.
"""

import os
from typing import List, Tuple
from PIL import Image, ImageDraw, ImageFont


class Lane4DataCardRenderer:
    """
    Renders deterministic statistical ranking cards for Shorts & TikTok.
    """

    WIDTH = 1080
    HEIGHT = 1920
    BG_COLOR = (15, 18, 25)           # Deep slate navy
    CARD_BG = (25, 30, 42)            # Lighter card container
    ACCENT_COLOR = (0, 225, 180)       # Electric cyan / mint
    SECONDARY_ACCENT = (140, 100, 255) # Electric violet
    TEXT_COLOR = (245, 245, 250)      # Bright off-white
    SUBTEXT_COLOR = (160, 170, 190)   # Muted slate

    def __init__(self):
        self.font_title = self._get_font(64, bold=True)
        self.font_subtitle = self._get_font(36, bold=False)
        self.font_bar_label = self._get_font(38, bold=True)
        self.font_bar_val = self._get_font(38, bold=True)
        self.font_footer = self._get_font(28, bold=False)

    def _get_font(self, size: int, bold: bool = False):
        font_paths = [
            "C:/Windows/Fonts/segoeui.ttf" if not bold else "C:/Windows/Fonts/segoeuib.ttf",
            "C:/Windows/Fonts/arial.ttf" if not bold else "C:/Windows/Fonts/arialbd.ttf",
            "C:/Windows/Fonts/consola.ttf"
        ]
        for p in font_paths:
            if os.path.exists(p):
                try:
                    return ImageFont.truetype(p, size)
                except Exception:
                    pass
        return ImageFont.load_default()

    def render_ranking_card(
        self,
        title: str,
        subtitle: str,
        items: List[Tuple[str, float, str]], # [(Label, NormalizedPercent 0..100, FormattedValue)]
        source_attribution: str,
        output_path: str
    ) -> str:
        """
        Renders a 1080x1920 vertical ranking infographic.
        """
        img = Image.new("RGB", (self.WIDTH, self.HEIGHT), color=self.BG_COLOR)
        draw = ImageDraw.Draw(img)

        # 1. Header Box
        draw.text((80, 180), title.upper(), fill=self.TEXT_COLOR, font=self.font_title)
        draw.text((80, 260), subtitle, fill=self.ACCENT_COLOR, font=self.font_subtitle)

        # 2. Horizontal divider
        draw.line([(80, 320), (self.WIDTH - 80, 320)], fill=(40, 48, 65), width=2)

        # 3. Render Data Bars
        start_y = 380
        bar_height = 54
        spacing = 130
        max_bar_width = self.WIDTH - 160 - 240 # Space for labels and numbers

        for i, (label, pct, val_str) in enumerate(items[:8]):
            curr_y = start_y + i * spacing

            # Rank indicator
            rank_str = f"#{i+1}"
            draw.text((80, curr_y), rank_str, fill=self.SECONDARY_ACCENT, font=self.font_bar_label)

            # Country/Item label
            draw.text((140, curr_y), label, fill=self.TEXT_COLOR, font=self.font_bar_label)

            # Value string (right aligned)
            draw.text((self.WIDTH - 80 - 180, curr_y), val_str, fill=self.ACCENT_COLOR, font=self.font_bar_val)

            # Bar background
            bar_y = curr_y + 48
            bar_x0 = 80
            bar_x1 = self.WIDTH - 80
            draw.rounded_rectangle([(bar_x0, bar_y), (bar_x1, bar_y + bar_height)], radius=8, fill=self.CARD_BG)

            # Filled bar
            fill_width = max(10, int((pct / 100.0) * (bar_x1 - bar_x0)))
            fill_color = self.ACCENT_COLOR if i == 0 else (60, 130, 240)
            draw.rounded_rectangle([(bar_x0, bar_y), (bar_x0 + fill_width, bar_y + bar_height)], radius=8, fill=fill_color)

        # 4. Footer & Source Attribution
        footer_text = f"Source: {source_attribution} • Generated by StatPulse Global"
        draw.text((80, self.HEIGHT - 160), footer_text, fill=self.SUBTEXT_COLOR, font=self.font_footer)

        # Ensure output directory exists
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        img.save(output_path, quality=95)
        return output_path
