import datetime
MAX_FUTURE_CLOCK_SKEW_SECONDS = 300
MAX_EVIDENCE_AGE_SECONDS = 172800

fresh_time = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
# first_observed_map uses h.get("timestamp_utc") from history.
# h.get("timestamp_utc") is generated by _history_entry -> datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
h_timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
e_observed_at = fresh_time

diff = (datetime.datetime.strptime(h_timestamp, "%Y-%m-%dT%H:%M:%SZ") - datetime.datetime.strptime(e_observed_at, "%Y-%m-%dT%H:%M:%SZ")).total_seconds()
print("diff:", diff)
print("cond 1:", -MAX_FUTURE_CLOCK_SKEW_SECONDS <= diff)
print("cond 2:", diff <= MAX_EVIDENCE_AGE_SECONDS)

# What if e_observed_at is 2026-01-01T00:00:00Z?
e_observed_at = "2026-01-01T00:00:00Z"
diff = (datetime.datetime.strptime(h_timestamp, "%Y-%m-%dT%H:%M:%SZ") - datetime.datetime.strptime(e_observed_at, "%Y-%m-%dT%H:%M:%SZ")).total_seconds()
print("\nstale diff:", diff)
print("cond 1:", -MAX_FUTURE_CLOCK_SKEW_SECONDS <= diff)
print("cond 2:", diff <= MAX_EVIDENCE_AGE_SECONDS)

