// Courier Supervisor Plane P0 — Types & Constants
// Enforces strict process ownership, stall thresholds, per-machine resource limits, and safety invariants.

const LEASE_STATUS = Object.freeze({
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  WAITING_VALID: 'WAITING_VALID',
  PROGRESSING: 'PROGRESSING',
  STALLED: 'STALLED',
  HUNG: 'HUNG',
  ORPHANED: 'ORPHANED',
  DUPLICATE: 'DUPLICATE',
  EXECUTION_UNCERTAIN: 'EXECUTION_UNCERTAIN',
  COMPLETED: 'COMPLETED',
  TERMINATED: 'TERMINATED',
  HUMAN_GATE: 'HUMAN_GATE'
});

const SUPERVISOR_DECISION = Object.freeze({
  KEEP_RUNNING: 'KEEP_RUNNING',
  WAIT: 'WAIT',
  CHECK_PROGRESS: 'CHECK_PROGRESS',
  CAPTURE_DIAGNOSTIC: 'CAPTURE_DIAGNOSTIC',
  TERMINATE_ORPHAN: 'TERMINATE_ORPHAN',
  TERMINATE_DUPLICATE: 'TERMINATE_DUPLICATE',
  TERMINATE_HUNG: 'TERMINATE_HUNG',
  BLOCK_EXECUTION_UNCERTAIN: 'BLOCK_EXECUTION_UNCERTAIN',
  HUMAN_GATE: 'HUMAN_GATE',
  NO_ACTION: 'NO_ACTION'
});

const RESOURCE_STATE = Object.freeze({
  NORMAL: 'NORMAL',
  BUSY: 'BUSY',
  PRESSURE: 'PRESSURE',
  THERMAL_PRESSURE: 'THERMAL_PRESSURE',
  RECOVERY: 'RECOVERY',
  UNKNOWN: 'UNKNOWN'
});

const RESOURCE_ACTION = Object.freeze({
  ALLOW: 'ALLOW',
  ALLOW_LIGHT_ONLY: 'ALLOW_LIGHT_ONLY',
  HOLD_NEW_HEAVY: 'HOLD_NEW_HEAVY',
  RECOMMEND_REROUTE: 'RECOMMEND_REROUTE',
  DIAGNOSE: 'DIAGNOSE',
  RECOVERY_MODE: 'RECOVERY_MODE'
});

const EVENT_TYPE = Object.freeze({
  PROCESS_REGISTERED: 'PROCESS_REGISTERED',
  HEARTBEAT: 'HEARTBEAT',
  PROGRESS_OBSERVED: 'PROGRESS_OBSERVED',
  STALL_CHECK: 'STALL_CHECK',
  DIAGNOSTIC_CAPTURED: 'DIAGNOSTIC_CAPTURED',
  STATE_CLASSIFIED: 'STATE_CLASSIFIED',
  PROCESS_TERMINATED: 'PROCESS_TERMINATED',
  PROCESS_RETAINED: 'PROCESS_RETAINED',
  ORPHAN_DETECTED: 'ORPHAN_DETECTED',
  DUPLICATE_DETECTED: 'DUPLICATE_DETECTED',
  EXECUTION_UNCERTAIN: 'EXECUTION_UNCERTAIN',
  HUMAN_GATE: 'HUMAN_GATE',
  RESTART_RECONCILIATION: 'RESTART_RECONCILIATION',
  TASK_HYGIENE_COMPLETED: 'TASK_HYGIENE_COMPLETED'
});

const THRESHOLDS = Object.freeze({
  SOFT_CHECK_AFTER_SECONDS: 300,       // 5 minutes
  DIAGNOSTIC_AFTER_SECONDS: 900        // 15 minutes
});

const SAFETY_INVARIANTS = Object.freeze({
  AUTONOMOUS_SPEND_LIMIT_EUR: 0,
  REAL_TRADES: 0,
  REAL_FUNDS_TOUCHED: 'NO',
  REAL_POSITIONS_CHANGED: 0,
  REAL_WALLETS_CONNECTED: 'NO',
  WALLET_SIGNING: 'NO'
});

const DEFAULT_MACHINE_CONCURRENCY = Object.freeze({
  MAC: {
    MAX_CONCURRENT_HEAVY_LOCAL_TASKS: 1
  },
  WINDOWS: {
    MAX_CONCURRENT_HEAVY_LOCAL_TASKS: 4
  }
});

module.exports = {
  LEASE_STATUS,
  SUPERVISOR_DECISION,
  RESOURCE_STATE,
  RESOURCE_ACTION,
  EVENT_TYPE,
  THRESHOLDS,
  SAFETY_INVARIANTS,
  DEFAULT_MACHINE_CONCURRENCY
};
